### PR TITLE
About OWASP Summit 2017 page has been created but is not finished

### PR DESCRIPTION
**Pull request by VasBu**
@fzipi , please check the technical perspective. This is my first a bit bigger edit of hugo website. I tried to followed instructions but please take a look.

@DinisCruz , @devseccon, @Lisa-devseccon , please take some time to check the textual description under all chapters in the page including the caption under every image. 

**IMPORTANT:** The chapter titled as "The Legacy" don't have textual description. I wrote some helper text formatted with gray italic font thus will help you to get the idea about this chapter.

### CODE REVIEW

**Comment by VasBu** [comment]
@fzipi , Thank you for the response. 
I asked @Lisa-devseccon to provide some specific header banner.

**Comment by Lisa-devseccon** [comment]
@VasBu what will be on this page? Perhaps you can publish it with the default banner for now, so I can take a look at the content.

**Comment by fzipi** [comment]
@VasBu I propose to commit the changes, but taking out the link from the `config.toml` so everyone can see it but it is not linked yet. Then send by PM in Slack the link to the page to the reviewers.

**Comment by VasBu** [comment]
@fzipi , I just removed the link from the main menu. If you can merge to master and we go live with this change, I can share the link to other reviewers so they can see it.

**Pull request merged**
